### ISSUE TITLE
Unable to dispatch or access any redux state becasue it is rendering in a new "div" element everytime

### ISSUE THREAD

**Issue by saswat3115** [prezly/react-promise-modal#2]

**Comment by e1himself** [comment]
Hi @saswat3115 

Thanks for submitting this issue.

You are absolutely right that it's not possible to use Redux state or React context for the modal spawned by the `@prezly/react-promise-modal`.

But this is not a bug, this is by design. 

`@prezly/react-promise-modal` sacrifices React _declarative UI_ approach to gain its super-simple _imperative_ API. The spawned modals are required to be completely independent and isolated from the main app context. They are *uncontrolled*. Similar to how the good-old [window.confirm()](https://developer.mozilla.org/en-US/docs/Web/API/Window/confirm) function works &mdash; you spawn it and wait for result, without being able to control or update it.

If you need Redux state inside a modal, then `@prezly/react-promise-modal` is not the right tool for the job. Instead you have to use Redux-way. Please see this StackOverflow thread: https://stackoverflow.com/questions/35623656/how-can-i-display-a-modal-dialog-in-redux-that-performs-asynchronous-actions/35641680#35641680

**Comment by e1himself** [comment]
@saswat3115

Even though you don't have access to React context and thus Redux state, you can still use this library with Redux.

You just need to accept the fact that the modal is _uncontrolled_. And opt-out dispatching any Redux actions from within the modal -- instead you should rely on the promise return value to communicate between the modal and the parent code.

This won't be "redux-way" though.

**Comment by e1himself** [comment]
This issue has been properly addressed in v2:
https://github.com/prezly/react-promise-modal/tree/99118c3300490d94382ea7147bbbb58dffa90718
