### ISSUE TITLE
React 18 issue

### ISSUE THREAD

**Issue by mburakkalkan** [prezly/react-promise-modal#9]
Although upgraded to react-promise-modal 0.3.0, I am getting the warning ReactDOM.render is no longer supported in React 18.

(Using a pure javascript project not typescript.)

![image](https://github.com/prezly/react-promise-modal/assets/4182925/95bc55e6-0d6b-42d7-b58c-fdd7c28989d1)

![image](https://github.com/prezly/react-promise-modal/assets/4182925/9d30c011-e5e7-4913-a502-49f64e06a8c7)

![image](https://github.com/prezly/react-promise-modal/assets/4182925/8d404d32-341a-49b6-9f18-afc46edc6ad7)

**Comment by e1himself** [comment]
Hey @mburakkalkan! 

This is weird. It seems like the 0.3.0 version was somehow published with the old code. 

I've just published [0.3.1](https://github.com/prezly/react-promise-modal/releases/tag/v0.3.1), which should contain the latest React 18 compatible code. Please give it a try to confirm the issue is fixed.

Thank you!

**Comment by mburakkalkan** [comment]
Hi @e1himself, sorry for my late answer. Yes, I tried with 0.3.1 and seems it fixed now. Thank you
